# Generated by Django 5.1.5 on 2025-01-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_usersurvey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey_type',
            field=models.CharField(choices=[('기업용', '기업용'), ('개인용', '개인용')], default='개인용', max_length=20),
        ),
    ]
