# Generated by Django 5.1.5 on 2025-01-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_usersurvey_answers_usersurvey_survey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='course_type',
            field=models.CharField(choices=[('비전하우스', '비전하우스'), ('리더십', '리더십'), ('기업가정신', '기업가정신')], default='비전하우스', max_length=20),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='is_pre_lecture',
            field=models.BooleanField(default=True),
        ),
    ]
