# Generated by Django 5.1.5 on 2025-01-23 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_usersurvey_course_type_usersurvey_is_pre_lecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating'), ('text', 'Text'), ('radio', 'Radio')], default='rating', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.coursetype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course_type', 'question', 'order')},
            },
        ),
        migrations.AddField(
            model_name='coursetype',
            name='survey_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_types', to='survey.surveytype'),
        ),
        migrations.CreateModel(
            name='SurveyTypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('survey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.surveytype')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('survey_type', 'question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserSurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('pre', 'Pre-Lecture'), ('post', 'Post-Lecture')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.coursetype')),
                ('survey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_value', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.usersurveyresponse')),
            ],
        ),
        migrations.DeleteModel(
            name='UserSurvey',
        ),
    ]
