# Generated by Django 5.1.5 on 2025-01-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_coursetype_question_surveytype_coursetypequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating'), ('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], default='rating', max_length=10),
        ),
    ]
