# Generated by Django 5.1.5 on 2025-02-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_question_options_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
