# Generated by Django 5.1.5 on 2025-02-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
