# Generated by Django 5.1.5 on 2025-02-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_remove_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
