# Generated by Django 5.1.5 on 2025-02-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_company_remove_user_company_name_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='programs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
