# Generated by Django 5.1.5 on 2025-02-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_company_programs'),
        ('survey', '0010_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='programs',
        ),
        migrations.AddField(
            model_name='company',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.coursetype'),
        ),
    ]
