[Service]
WorkingDirectory=/var/www/RebootCommons/backend/backend
ExecStart=
ExecStart=/root/.local/share/virtualenvs/backend-_HH0JIMF/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 backend.wsgi:application
Restart=on-failure
RestartSec=5s
